version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      - server
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - BACKEND_URL=http://localhost:8080/
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - /app/node_modules
      - ./server:/app
    networks:
      - app-network
networks:
  app-network:
    driver: bridge