AWSTemplateFormatVersion: "2010-09-09"
Resources:
  RDSPostgreSQL:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: postgres
      DBInstanceClass: db.t3.micro
      AllocatedStorage: 20
      PubliclyAccessible: false
      VPCSecurityGroups:
        - !Ref ECSFargateSecurityGroup
      # Make sure to define Params before using them here
      # Command line: aws ssm put-parameter --name /simpleapp/db/username --value admin --type SecureString
      # Command line: aws ssm put-parameter --name /simpleapp/db/password --value admin123 --type SecureString
      MasterUsername: !Sub "{{resolve:ssm:/myapp/db/username}}"
      MasterUserPassword: !Sub "{{resolve:ssm:/myapp/db/password}}"
